DECLARE
	CURSOR C_DEPT IS 
		SELECT * FROM DEPARTAMENTOS
		ORDER BY PRESUPUESTO_DE;
	TYPE T_TABLA IS TABLE OF DEPARTAMENTOS%ROWTYPE
		INDEX BY BINARY_INTEGER;
	V_TABLA T_TABLA;
	i	BINARY_INTEGER;
BEGIN
	-- Rellenar la tabla con el cursor
	FOR reg IN C_DEPT LOOP
		V_TABLA(reg.COD_DE) := reg;
	END LOOP;
	DBMS_OUTPUT.PUT_LINE('Con LOOP');
	i := V_TABLA.FIRST;
	LOOP
		DBMS_OUTPUT.PUT_LINE(V_TABLA(i).NOMBRE_DE||' '||V_TABLA(i).COD_DE);
		i := V_TABLA.NEXT(i);
		EXIT WHEN NOT V_TABLA.EXISTS(i);
	END LOOP;
	DBMS_OUTPUT.PUT_LINE('Con WHILE');
	i := V_TABLA.FIRST;
	WHILE V_TABLA.EXISTS(i) LOOP
		DBMS_OUTPUT.PUT_LINE(V_TABLA(i).NOMBRE_DE||' '||V_TABLA(i).COD_DE);
		i := V_TABLA.NEXT(i);
	END LOOP;
	DBMS_OUTPUT.PUT_LINE('Con WHILE al reves');
	i := V_TABLA.LAST;
	WHILE V_TABLA.EXISTS(i) LOOP
		DBMS_OUTPUT.PUT_LINE(V_TABLA(i).NOMBRE_DE||' '||V_TABLA(i).COD_DE);
		i := V_TABLA.PRIOR(i);
	END LOOP;
END;
/