--Ejemplos Rapidos Examen
--CREATE
CREATE TABLE PRODUCTOS(
	COD		NUMBER(5),		
	NOMBRE	VARCHAR2(15), 
	PAIS	NUMBER(5),
	CONSTRAINT PK_PROD PRIMARY KEY(COD),
	CONSTRAINT CK_NOMB CHECK(NOMBRE=UPPER(NOMBRE)), 
	CONSTRAINT FK_PAIS FOREIGN KEY (PAIS) REFERENCES PAIS 
);

--otro 

CREATE TABLE PEDIDOS(
NIF               VARCHAR2(10) ,
ARTICULO          VARCHAR2(20) ,
COD_FABRICANTE    NUMBER(3) ,
PESO              NUMBER(3) ,
CATEGORIA         VARCHAR2(10),
FECHA_PEDIDO      DATE PRIMARY KEY,
UNIDADES_PEDIDAS  NUMBER(4),
CONSTRAINT articulos_fk FOREIGN KEY(ARTICULO,PESO,CATEGORIA) REFERENCES ARTICULOS,
CONSTRAINT tiendas_fk FOREIGN KEY (NIF) REFERENCES TIENDAS,
CONSTRAINT fabricante_fk FOREIGN KEY (COD_FABRICANTE) REFERENCES FABRICANTES
) ;

--INSERT

INSERT INTO EMPLE 
SELECT DISTINCT 1111,'GARCIA', 'ANALISTA', 7566, SYSDATE, 2000, 120, DEPT_NO
FROM EMPLE 
WHERE DEPT_NO = ( SELECT DEPT_NO 
                FROM EMPLE              
		GROUP BY DEPT_NO
                HAVING COUNT(*) = ( SELECT MAX(COUNT(*)) 
				        FROM EMPLE 
					GROUP BY DEPT_NO) );


 INSERT INTO  EMPLE30 (EMP_NO,APELLIDO, OFICIO, DIR, FECHA_ALT, SALARIO, COMISION, DEPT_NO)	
     SELECT EMP_NO,APELLIDO, OFICIO, DIR, FECHA_ALT, SALARIO, COMISION, DEPT_NO
	 FROM EMPLE 
	 WHERE DEPT_NO=30;

o VALUES(valores de la tabla)

--UPDATE
UPDATE NombreTabla
SET col1 = valor1, ...,coln = valorn
WHERE colx = (SELECT ...);

UPDATE NombreTabla
SET (col1, col2,...) = (SELECT columna1, columna2, ...)
WHERE condición;

UPDATE NombreTabla
SET col1 = (SELECT columna1 ...), col2 = (SELECT columna1 ...), ...
WHERE condición;

--DELETE

DELETE FROM CENTROS WHERE COD_CENTRO=50;

DELETE FROM DEPART 
WHERE DEPT_NO IN(SELECT DEPT_NO 
				   FROM EMPLE 
			   GROUP BY DEPT_NO 
				 HAVING COUNT(*) < 4);