--Act 1 0.9
CREATE TABLE Fabrica(
COD_FABRICANTE NUMBER(3) CONSTRAINT COD_FABRICANTE PRIMARY KEY,
NOMBRE VARCHAR2(15)  CHECK(NOMBRE=UPPER(NOMBRE)),
PAIS VARCHAR2(15)  CHECK(PAIS=UPPER(PAIS))
);
--Falta nombre en los 2 constraint de check.(-0.1 al ser el mismo error)
--Act 2 -- 0.8
CREATE TABLE Articulos(
ARTICULO VARCHAR2(20),
COD_FABRICANTE NUMBER(3),
PESO NUMBER(3),
CATEGORIA VARCHAR2 (10) ,
PRECIO_VENTA NUMBER(4) CONSTRAINT PRECIO_VENTA CHECK(PRECIO_VENTA>0),
PRECIO_COSTO NUMBER(4) CONSTRAINT PRECIO_COSTO CHECK(PRECIO_COSTO>0),
EXISTENCIAS NUMBER(5),
CONSTRAINT Artuculos_pk PRIMARY KEY ( ARTICULO , COD_FABRICANTE , PESO , CATEGORIA ),
CONSTRAINT CATEGORIA_ck CHECK (CATEGORIA
='Primera'
OR CATEGORIA ='Segunda'
OR CATEGORIA ='Tercera'),
CONSTRAINT ARTICULO_COD_FABRICANTE_fk FOREIGN KEY(COD_FABRICANTE)
REFERENCES Fabrica
ON DELETE CASCADE
);
--Falta comprobar que el peso sea menor 0 (-0.2)

--Act 3 --------------------------- 1.8

CREATE TABLE TIENDAS(
NIF VARCHAR2 (10) PRIMARY KEY,
NOMBRE VARCHAR2 (20),
DIRECCION VARCHAR2 (20),
POBLACION VARCHAR2 (20),
PROVINCIA VARCHAR2 (20) CHECK(PROVINCIA = UPPER(PROVINCIA)),
CODPOSTAL NUMBER (5)
);
--Falta nombre de la clave primaria NIF (-0.1)
--Falta nombre del constraint check de PROVINCIA(-0.1)

--Act 4 ------------------------------ 3

CREATE TABLE PEDIDOS(
NIF VARCHAR2 (10),
ARTICULO VARCHAR2(10),
COD_FABRICANTE NUMBER(3),
PESO NUMBER(3),
CATEGORIA VARCHAR2(10),
FECHA_PEDIDOS DATE,
UNIDADES_PEDIDAS NUMBER(4) CONSTRAINT UNIDADES_PEDIDAS CHECK(UNIDADES_PEDIDAS>0),
CONSTRAINT PEDIDOS_PK PRIMARY KEY(NIF,ARTICULO,COD_FABRICANTE,PESO,CATEGORIA,FECHA_PEDIDOS),
CONSTRAINT PEDIDOS_CATEGORIA_ck CHECK (CATEGORIA
='Primera'
OR CATEGORIA ='Segunda'
OR CATEGORIA ='Tercera'),
CONSTRAINT PEDIDOS_COD_FABRICANTE_fk FOREIGN KEY(COD_FABRICANTE)
REFERENCES Fabrica
ON DELETE CASCADE,
CONSTRAINT PEDIDOS_fk FOREIGN KEY(ARTICULO,COD_FABRICANTE,PESO,CATEGORIA)
REFERENCES Articulos
ON DELETE CASCADE,
CONSTRAINT PEDIDOS_NIF_fk FOREIGN KEY(NIF)
REFERENCES TIENDAS
ON DELETE CASCADE
);

--Act 5 ------------------------------3
 
CREATE TABLE VENTAS(
NIF VARCHAR2 (10),
ARTICULO VARCHAR2(20),
COD_FABRICANTE NUMBER(3),
PESO NUMBER(3),
CATEGORIA VARCHAR2(10),
FECHA_VENTA DATE,
UNIDADES_VENDIDAS NUMBER(4)
);

ALTER TABLE VENTAS
MODIFY(
CONSTRAINT VENTAS_PK PRIMARY KEY(NIF,ARTICULO,COD_FABRICANTE,PESO,CATEGORIA,FECHA_VENTA),
CONSTRAINT VENTAS_COD_FABRICANTE_fk FOREIGN KEY(COD_FABRICANTE)
REFERENCES Fabrica
ON DELETE CASCADE,
CONSTRAINT VENTAS_UNIDADES_VENDIDAS_ck CHECK(UNIDADES_VENDIDAS>0),
CONSTRAINT VENTAS_CATEGORIA_ck CHECK (CATEGORIA
='Primera'
OR CATEGORIA ='Segunda'
OR CATEGORIA ='Tercera'),
CONSTRAINT VENTAS_fk FOREIGN KEY(ARTICULO,COD_FABRICANTE,PESO,CATEGORIA)
REFERENCES Articulos,
CONSTRAINT VENTAS_NIF_fk FOREIGN KEY(NIF)
REFERENCES TIENDAS
ON DELETE CASCADE
);

--Total : 9.5