--Act 1
CREATE TABLE Fabrica(
COD_FRABRICANTE NUMBER(3) CONSTRAINT COD_FRABRICANTE PRIMARY KEY,
NOMBRE VARCHAR2(15)  CHECK(NOMBRE=UPPER(NOMBRE)),
PAIS VARCHAR2(15)  CHECK(PAIS=UPPER(PAIS))
);
--Act 2
