--Tablas EMPLE Y DEPART
--1
SELECT *
FROM EMPLE
where APELLIDO LIKE 'A%' and OFICIO LIKE '%E%';

--2
SELECT APELLIDO , OFICIO , LOC
FROM EMPLE , DEPART
WHERE OFICIO = 'ANALISTA';

--3
SELECT EMP_NO , OFICIO , SALARIO , FECHA_ALT
FROM EMPLE;

SELECT APELLIDO , OFICIO , SALARIO , FECHA_ALT
FROM EMPLE
WHERE OFICIO = (SELECT OFICIO
                FROM EMPLE
                WHERE APELLIDO = 'JIMENEZ') 
OR SALARIO >= (SELECT SALARIO
                FROM EMPLE
                WHERE APELLIDO = 'FERNANDEZ');

--4 

SELECT APELLIDO , OFICIO , SALARIO
FROM EMPLE
WHERE SALARIO = (SELECT SALARIO
                FROM EMPLE
                WHERE APELLIDO = 'FERNANDEZ');

--5

SELECT APELLIDO , OFICIO
FROM EMPLE
WHERE OFICIO = (SELECT OFICIO
                FROM EMPLE
                WHERE APELLIDO = 'JIMENEZ');