CREATE TABLE Trabajadores(
DNI VARCHAR(9) CONSTRAINT DNI_TRABAJADOR_pk PRIMARY KEY,
NOMBRE VARCHAR2(30),
APELLIDOS VARCHAR2 (50)
);

CREATE TABLE 

CREATE TABLE Ticket(
ID_TICKET NUMBER(9) CONSTRAINT ID_TICKET_pk PRIMARY KEY,
NUM_ASIENTO NUMBER (15),
NUM_SALA NUMBER (5)
);

CREATE TABLE Cliente(
DNI VARCHAR(9) CONSTRAINT DNI_CLIENTE_pk PRIMARY KEY,
NOMBRE VARCHAR2(30)
);

CREATE TABLE Tarjeta(
ID_TARJETA NUMBER(9) CONSTRAINT ID_TARJETA_pk PRIMARY KEY
);

CREATE TABLE Descuento(
ID_DESCUENTO NUMBER(10) CONSTRAINT ID_DESCUENTO_pk PRIMARY KEY,
TIPO VARCHAR2(20) CONSTRAINT TIPO_ck CHECK(
    TIPO = "Entrada"
    OR TIPO = "Palommitas"
    OR TIPO = "Nacho y chuches"
)
);